import { createClient } from "@supabase/supabase-js";

const supabaseKeyBypass = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5cnpvaHJqbWZ1aWxteHF6Z3JxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyNDEyMDkxMywiZXhwIjoyMDM5Njk2OTEzfQ.Jn75tEE1WZKMk5l3j4RKROig82_kjr_6_blkWUihQoA";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5cnpvaHJqbWZ1aWxteHF6Z3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQxMjA5MTMsImV4cCI6MjAzOTY5NjkxM30.FAFBnmTRXwjYeF3tMxuQ7yNHWxqtlm2zGxlpQsLTJ_4"
const supabaseurl = "https://yyrzohrjmfuilmxqzgrq.supabase.co"

const benSupabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3eGp2d21zcHJmcHp5dHR2bmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU4NDMwMjcsImV4cCI6MjA0MTQxOTAyN30.OO4ifaEP1qeHLPKL9ILiz_meJxNu3B-TQKU7PHPvQdA";
const benSupabaseurl = "https://iwxjvwmsprfpzyttvngz.supabase.co";
const benSupabaseKeyAlpha = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3eGp2d21zcHJmcHp5dHR2bmd6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyNTg0MzAyNywiZXhwIjoyMDQxNDE5MDI3fQ.zRB0hlIUxMahMdMXaR9qN-GDeWXiMrAS9cG28PI0u5I"

const supabase = createClient(supabaseurl, supabaseKey)




export default supabase
